### ISSUE TITLE
ValueError: could not broadcast input array from shape (178,164,3) into shape (222,206,3)

### ISSUE THREAD

**Issue by chinmaynehate** [Arlen0615/Convert-own-data-to-MNIST-format#5]
Can anybody explain?
99% completeTraceback (most recent call last):
  File "Densenet_MNIST.py", line 215, in <module>
    main(sys.argv)
  File "Densenet_MNIST.py", line 199, in main
    labelsAndFiles, argv[2])
  File "Densenet_MNIST.py", line 160, in make_arrays
    trainImagedata[i] = images[i]
ValueError: could not broadcast input array from shape (178,164,3) into shape (222,206,3)

**Comment by Adesoji1** [comment]
@chinmaynehate how did you solve this problem
